# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-get" do
  desc "Better way to clone, organize and manage multiple git repositories"
  homepage "https://github.com/grdl/git-get/"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-get"

  on_macos do
    on_intel do
      url "https://github.com/grdl/git-get/releases/download/v0.6.0/git-get_0.6.0_darwin_amd64vv1.tar.gz",
        verified: "github.com/grdl/git-get"
      sha256 "8bb92fd5e619a1b7cbcdcea0187a615f27b8a105be3aa2023517ce174bef8f8d"
    end
    on_arm do
      url "https://github.com/grdl/git-get/releases/download/v0.6.0/git-get_0.6.0_darwin_arm64.tar.gz",
        verified: "github.com/grdl/git-get"
      sha256 "6453b21e735463fa160d662f79e82541565d9c6d2bbdce27449eefeb574b2726"
    end
  end

  postflight do
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/git-get", "#{HOMEBREW_PREFIX}/bin/git-list"]
  end

  # No zap stanza required
end
