# This file was generated by GoReleaser. DO NOT EDIT.
class GitGet < Formula
  desc "A better way to clone, organize and manage git repositories."
  homepage "https://github.com/grdl/git-get/"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/grdl/git-get/releases/download/v0.0.2/git-get_0.0.2_macOS_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "9757dfe7b5db8993ef6739aebd1122a521a81349bac9032e0c78d68a70c4b85e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/grdl/git-get/releases/download/v0.0.2/git-get_0.0.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "fb7037fa3720288418458a34ca01649fee01588956733bf3bb25879a3f7fed94"
    end
  end

  def install
    bin.install "git-get"
  end

  test do
    system "git-get --version"
  end
end
