# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sample < Formula
  desc "Sample :golang: Go application to be used as a base template for other projects."
  homepage "https://github.com/grdl/sample/"
  version "0.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grdl/sample/releases/download/v0.0.1/sample_0.0.1_macOS_x86_64.tar.gz"
      sha256 "acd01e12ce14f893518785829e09872b3227b85f7aa97dbb592527147c70904a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/grdl/sample/releases/download/v0.0.1/sample_0.0.1_macOS_arm64.tar.gz"
      sha256 "653e40ecd3ef5aa9c509a772402dd331fbc564ece2c4c72ab9d57f1dfc51e7c7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grdl/sample/releases/download/v0.0.1/sample_0.0.1_linux_x86_64.tar.gz"
      sha256 "788e18bfcc7d44e76e6b28ac861549baadc297141fe018940535549245b00d28"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grdl/sample/releases/download/v0.0.1/sample_0.0.1_linux_arm64.tar.gz"
      sha256 "a5dd2780b6e4da2385466691af81393eddeaa6a2bc1458443023b0fc21f1cc57"
    end
  end

  def install
    bin.install "sample"
  end

  test do
    system "sample --version"
  end
end
