# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zname < Formula
  desc ": search through your cloud DNS records"
  homepage "https://github.com/grdl/zname/"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grdl/zname/releases/download/v0.0.2/zname_0.0.2_macOS_x86_64.tar.gz"
      sha256 "4dbf2696e2361fafd568a220feaf63a91c4dd243484cf02788544fdbbf13cc11"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grdl/zname/releases/download/v0.0.2/zname_0.0.2_linux_x86_64.tar.gz"
      sha256 "bb0b7cd2d361137bf38bcf57502f3f54d9eee666fae2386e4c50ca05ba1a8d5f"
    end
  end

  def install
    bin.install "zname"
  end

  test do
    system "zname", "--version"
  end
end
